### ISSUE TITLE
Some EUnit Tests are Non-Deterministic 

### ISSUE THREAD

**Issue by jxs1** [ArchainTeam/archain#5]
Some EUnit Tests are Non-Deterministic

**Comment by samcamwilliams** [comment]
Am I right in thinking that this is just the rejection of forged nonce test? That is happening because a randomly chosen nonce will occasionally actually satisfies the requirements of the difficulty algorithm. Perhaps an appropriate fix is to generate a random binary that starts with a 1? We could even just use a static nonce that we know does not satisfy the requirements. 

Are there any other cases of non-determinism that we know about? 

Sam

**Comment by wrj-arc** [comment]
This was a bug with the detect_invalid_nonce_test() function, and has now been fixed.
